### ISSUE TITLE
don't trust, verify

### ISSUE THREAD

**Issue by okwme** [vsergeev/evolve110#3]
i want to click but i won't allow myself til i can check the deployed code
https://etherscan.io/address/0xB8F2D890A60bFc679949bab7cE933a576Ba570aa#code

**Comment by vsergeev** [comment]
It turns out it's pretty difficult to find the exact Solidity compiler version used to build a contract from 4 years ago (before the compiler metadata was stored in the JSON output). Should have saved my package-lock.json.

**Comment by vsergeev** [comment]
I managed to find it. Fixed.
